### ISSUE TITLE
Resource not found

### ISSUE THREAD

**Issue by JayOram** [cossssmin/sendtest.email#51]
Hey always the second send of any email, to any address - 

Well, 💩.
SparkPost says: Resource not found

Could be true - it is a very popular tool now!!

**Comment by cossssmin** [comment]
Hi Jay,

I'm not able to replicate, can you please let me know what HTTP status code the Network tab in Chrome shows when it errors out like that?

[SparkPost's error codes page](https://www.sparkpost.com/docs/tech-resources/extended-error-codes/) says that's a 404, but it clearly works so I'm not really sure what it means.

**Comment by sshah-email** [comment]
Hey,

This has been happening for me too for the past week or so. As Jay said, occurs on and after the second send on the same address. In the Chrome network window I see:

Name: send
Initiator: App.vue:190
Size: 168 B
Time: 1.11s
Request URL: https://sendtest.email/.netlify/functions/send
Request Method: POST
Status Code: 404 
server: Netlify

**Comment by cossssmin** [comment]
I wonder if this is actually Akismet screwing up - I've recently added it as an extra security measure. As you can see, it also returns a 404 (on purpose):

https://github.com/cossssmin/sendtest.email/blob/bda5d434390ccd32e5c8cc90cb2da22a6d4d48df/src/lambda/send.js#L68-L75

I'll change the error message in an hour or so, since it's the same one returned by SparkPost's API - do let me know if the modal changes from `SparkPost says: Resource not found`.

Moving on, I'll experiment with invisible RECAPTCHA and if that works better I'll drop Akismet.

**Comment by cossssmin** [comment]
Updated - if this is about Akismet, it should now return a 403 Forbidden. Please let me know.

**Comment by sshah-email** [comment]
Many thanks for the update. It seems like it is an Askimet issue then as its returning error code 403 now as opposed to 404. Details:

* Name: send
* Initiator: app.af0334cb.js:1
* Size: 164 B
* Time: 1.01s
* Request URL: https://sendtest.email/.netlify/functions/send
* Request Method: POST
* Status Code: 403
* Date: Wed, 13 Nov 2019 13:28:30 GMT
* Server: Netlify

**Comment by cossssmin** [comment]
Bloody Akismet! 🙂 

Thanks for confirming, I'll try to test out invisible RECAPTCHA and replace Akismet as soon as possible.

**Comment by cossssmin** [comment]
Replaced Akismet with invisible reCAPTCHA, it should work better now.

**Comment by cossssmin** [comment]
Closing as resolved, feel free to re-open.
