### ISSUE TITLE
Cannot send emails because of JavaScript error in the console

### ISSUE THREAD

**Issue by hteumeuleu** [cossssmin/sendtest.email#90]
Hi! There's currently a JavaScript error in the console (all browsers): 

```
TypeError: can't access property "total_accepted_recipients", t.data.results is undefined App.vue:259:14
```

This prevents any email to be sent at the moment.

**Comment by cossssmin** [comment]
Hey, thanks for the heads up! Just tested and it works fine, I think SparkPost didn't return the `data.results` object properly.

It would be coming from this block:

https://github.com/cossssmin/sendtest.email/blob/7ea069cb6af0d846a15bdfe5f3b2f37a155f0122/src/App.vue#L259-L267

... which tries to show the 'success' modal only if the SparkPost API reported back a truthy value for that `results.total_accepted_recipients` key (i.e. it sent the email to the address you specified).

So it errored out because the `results` object didn't exist in the API response.

I'll try refactoring that code so it ensures `results` exists and if it doesn't, it shows an error or warning message in the modal.

**Comment by cossssmin** [comment]
Pushed a fix, feel free to reopen if you're still experiencing issues 👍
